### ISSUE TITLE
JS Error "No input file specified."

### ISSUE THREAD

**Issue by makkinga** [aryehraber/statamic-font-awesome#3] opened 2018-11-15 08:25 UTC
Hi @aryehraber,

I just installed this addon but keep getting a loading icon on the fieldset.

![image](https://user-images.githubusercontent.com/3294611/48539627-09bfee80-e8b8-11e8-8b7d-954a054f561c.png)

And some errors in the console:

![image](https://user-images.githubusercontent.com/3294611/48539726-4b509980-e8b8-11e8-8e7b-0ae5871fbf16.png)

Going to `/!/FontAwesome/icons` manually works fine

I run on a Forge Nginx server. I can provide more specs if necessary

**Comment by aryehraber** [comment] 2018-11-15 08:32
Hmm, can you try clearing the cache? The icons are fetched via the `FontAwesomeController` which grab some data from FontAwesome's GH repo, maybe something went wrong there and got cached incorrectly?

**Comment by makkinga** [comment] 2018-11-15 08:43
I don't think it even gets that far, `dd()`-ing at the start of `getIcons()` doesn't return my string. It does when I visit `/!/FontAwesome/icons` in the browser

**Comment by aryehraber** [comment] 2018-11-15 08:46
How strange! This is the first time I'm hearing/seeing this problem. I haven't tested this addon on the latest version(s) of Statamic so maybe something changed/broke along the way. 

If you are able to, please do some digging, otherwise I'll try and have a look in the coming days/weeks.

**Comment by makkinga** [comment] 2018-11-15 10:32
@aryehraber I tried it on a different server (Apache) and n earlier release (2.10.3) but still the same issue. Do you know how to easily install a specific older release?

**Comment by aryehraber** [comment] 2018-11-15 10:49
I just updated my local Statamic dev site to latest (v2.11.2), and the addon seems to be working fine.

Not really sure what to suggest tbh, sorry! Maybe it's something on the JS side, you can check the fieldtype itself by going to `/resources/assets/js/fieldtype.js` and debugging via the Network tab to see what responses come through.

**Comment by makkinga** [comment] 2018-11-15 11:52
Works in valet! So the problem must be somewere in the server configuration

**Comment by aryehraber** [comment] 2018-11-15 12:06
Ok, good to know! 

If you find out what the issue is and it's fixable via some server settings, feel free to submit a PR to the docs incase others run into this.

Closing for now, but feel free to reopen if needed!

**Closed by aryehraber** 2018-11-15 12:06 UTC
